[Eth]
NetworkId = 93819023
SyncMode = "fast"
LightPeers = 0

[Node]
UserIdent = "00"
DataDir = "/root/.ethereum"
KeyStoreDir = "/cwd/wallet"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPModules = ["db", "eth", "ne", "web3", "personal", "crypto-js"]
HTTPCors = ["https://remix.ethereum.org"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 0
NoDiscovery = true
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30000"