language: cpp
sudo: required
compiler:
    - gcc
dist:
    - Ubuntu
os:
    - linux
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-5 g++-5 cmake cmake-data
    - sudo apt-get install -y libjsoncpp-dev libsqlite3-0 libsqlite3-dev libboost-all-dev
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - src/utils/build_odb.sh || travis_terminate 1
    - src/utils/install_jsonrpccpp.sh || travis_terminate 1
    - wget https://s3.amazonaws.com/tc-travis/sgx-sdk.tar.gz && tar xf sgx-sdk.tar.gz -C /
install:
    - cd src/utils && ./build_gtest.sh && cd -
script:
    - ./src/lint.sh || travis_terminate 1
    - make -C src/Enclave/mbedtls-SGX
    - mkdir -p src/build && cd src/build && cmake .. && make all && make TestMain
    - ./TestMain
notifications:
  slack:
    secure: jsc58HqOjk0uJtipWAgHsjaL6Ee4N1YZ99wqtemZ7alk06dWsYyGdcGIGBS7F4m4YkrTg8QpoAIiJSFKCYM6W0C5nYSKn8SqF3MbulLfY428jVX4NgvdnydoXMJUw7JgvRckMNUcyE2EIIp7qvPF1q4ZZAyL5h1o7NGmZa83WRdU0InFM55wAqkGy5LPNWIjN1Uz6UOa/eKy/eVmUebkp9nMHvcJcJGWaZx6are282rgNs7Xbt6c+TdU082s6pcIWAs3ONrAg+CMGxFCi6bbx5KtBqHe/MZ/FCENgQC0dbivgghw4yLmY0CxSrK7/Zf7QYQe66P4joXNrGwmGiA7i//nkcRcDTtDHbzPPDBkIvWL8PNg6DskxMVc4S0poD4EYbAvtj7btGkAg5FWwT+QdQkuqnf+FkpORL1Eq9E86Y42PFmFONFMSrXzD0smc9b6zqErOd1kmfSApRjPoMvhZSxRE0CLCtMyHoMr3ZhWE1E0wyJrFerjPtKqNH4yDDJ04Omdr7FyatYeU59c0HWWlaa1ZE2A9vURZeRvZGaoNA9yOUpzbl0tYAoO2QUswz1s4R/3Wu3f7d199SJtUzQtnL1DxDaiG8b+K5xI4Ww6+9GEM2CyftbUTiWeCfKg7D/5KgUYBibzMAALPygnStoYedZd2jQ4N4/JIQKRlMJBcNo=
