sudo: required
services:
- docker
before_install:
- docker pull bl4ck5un/tc-sgx-sdk:latest
- docker run -v $(pwd):/tc -w /tc bl4ck5un/tc-sgx-sdk sh -c "scripts/build_gtest.sh"
script:
- make MAKE_FLAGS="" -C scripts
deploy:
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bl4ck5un/tc-core:Debug
  - docker push bl4ck5un/tc-core:Prerelease
  - docker push bl4ck5un/tc-relay
  on:
    branch: master
notifications:
  slack:
    secure: gtscAP0J7Y9WCGSpfSNosFn1bVxt3x1Rno71vGxCYmmkaji1LKmlwlU94ECpbe6UPVz+QgTn2jXupNa6EkQptJUNEVQd4bU3sPKT/OccF4opcmYEM0BROBg2LOIJnsCQX4lgM+C2cPtQLV7Z06ryDrLM0aykhHwS5tmWh+8w4eeDpZOVAoIkJJnrmEyPf95nY94KQHHtoHNG1YpPQA5hKv7nVdRi5WrFY4lS7b16Z1jYpPzlX49DMVzESxvEMKesc7o0MZmIjmXFYzckFMl+1YVDfIM4htw/aQtlg3ZDNPCcNVQYy5EsfxqZixxTBXRSaNlLOWaxuOhHluIZWNlM5i0Ku2PaLgvVFsGi1gNKs/FjZbLGkILxPNBGuXesp8ibSQchDdEYPsAnVSYPh5Gn3vV7NFvevJVvHFBSl6cbBqAfOYJE48yqxG5ZiRFutpWeYL1CB7CD4RL0IlKpN9pt2L5XzYs7KiMfEK0Vngk1GNmPmZkcTE/k3/zJ/sb7IecpjEWKdmzE05oxVddLFdNMee8eGjK6vohXxoQg1H1/behPE8b3pMuuP6nyED5IBFwYB/pe6ZkDygNqhMPqrZwBd5AnAnHMCJpEz13WiXCWF6RPSEXQ/4ThVWvAGgVcF7RjhmOYapykGcr/BBdvHGaVbU+T+LybgHMbupew1Tdp/mI=
env:
  matrix:
    secure: ks0u6+IFtJlFHpTAlDfhfx2ApEAhsyGdGozJXRVIvqklZkBCsPYUlhM7DP6WIDH3JdtT+ooRWz+8Rd6CCHqPHcJIkFzrYI75woyj2ztG3ZbWSjXbfAj9hJqFsdTvpnNuLLYVUwMGF9IsCSx7/mJRA3ye7jsjmX6wYBpoM1YfVHBH1u8Im4Vn6kojIR/fLtF6c7ZXEOsTwMYdRNzEko4Mj11nWNeooBPbcWyZDhZCXUJqbE95vBsrNqvh3doVzpSIqUzx9uSJAdnOrP+aUwenvSIJIe3qiD2IEUF1rBVMBWzP1nn4fFVhc5Of9HEe1A9gdhDYu3MgVoqwgJKl08PR/j9ivETiPUd2KN7RT7x+LqYMoXDuYaoHTXEaRDv2v+Q/MG7//eRTt8DAI3TU/nr4bM5lH9O5MWay2BylvPQyGZBFBkJEcwpA0hAQUdgEEBGoO9vVyKT4hCDq+AQK5yXt5G9P0z9WqWHDQro4EyCvMMauIbKcZgsKBr7FKRsMdxV3YFzBcnlNmzJNe2arW7EehjLM55eHuwnpQqWu803WfZOOIg5lBz8n3eh5OJqzv4I7SIqlmYtN4fCQMfY09ZK/3o/q70erJQWPsF7rYV4Agt/9Cc7L8gly19dSvmrtWV0OcI0muHXcDLs0ivOnfElHXsWJ9AxhpvlC6TBNgJZxXBw=
