language: cpp
sudo: required
compiler:
- gcc
dist:
- Ubuntu
os:
- linux
install:
- sudo apt-get install -qq cmake libjsoncpp-dev libjsonrpccpp-dev libjsonrpccpp-tools libsqlite3-0 libsqlite3-dev libboost-all-dev libmicrohttpd-dev
scripts:
- ./src/utils/build_gtest.sh
- mkdir -p build && cd build && cmake .. && make all
after_sucess:
- ./src/build/TestMain
