language: cpp
sudo: required
compiler:
- gcc
dist:
- Ubuntu
os:
- linux
install:
- sudo apt-get install -qq cmake libjsoncpp-dev libjsonrpccpp-dev libjsonrpccpp-tools libsqlite3-0 libsqlite3-dev libboost-all-dev libmicrohttpd-dev
scripts:
- ./compile-project.sh
after_sucess:
- ./run-tests.sh
