[Eth]
NetworkId = 4
SyncMode = "fast"
LightPeers = 20
DatabaseCache = 512
GasPrice = 20000000000
EnablePreimageRecording = false

[Eth.GPO]
Blocks = 10
Percentile = 50

[Node]
DataDir = "/root/.ethereum"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPModules = ["net", "web3", "eth", "admin", "personal", "txpool"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303"]
BootstrapNodesV5 = ["enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"

[Ethstats]
URL = "TownCrier:Respect my authoritah!@stats.rinkeby.io"

[Dashboard]
Host = "0.0.0.0"
Port = 8080
Refresh = 5000000000
