version: "2"
services:
    tc-core:
        image: "bl4ck5un/tc-core:Prerelease"
        network_mode: host
        devices:
          - /dev/isgx
        volumes:
          - ./supervisor:/supervisor
          - ../config/config-release:/config
    tc-relay:
        depends_on:
          - tc-core
        image: "bl4ck5un/tc-relay"
        network_mode: host
