version: "2"
services:
    tc-core:
        image: "bl4ck5un/tc-core:Debug"
        network_mode: host
        entrypoint: "tc"
    tc-relay:
        depends_on:
          - tc-core
        image: "bl4ck5un/tc-relay"
        network_mode: host
